name: SmallTownArtillery
favicon: null
layout_spectrum: 0.26245
typography_spectrum: 0.08279203996062279
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#011430'
    - '#fabb70'
    - '#fce786'
    - '#523735'
    - '#567e5d'
  brandStrength: 0.75
  lightness: 0.4919893539045006
  saturation: 0.1167887335177511
  rhythmicContrast: 0.20939399441704154
purpose: []
