name: SmallTownArtillery
favicon: null
layout_spectrum: 0.26245
typography_spectrum: 0.45767
title: Small Town Artillery
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030305'
    - '#ffffff'
    - '#d3d3dd'
    - '#8d5c47'
    - '#e54741'
  brandStrength: 0.8125
  lightness: 0.25
  saturation: 0.75
  rhythmicContrast: 0.5
purpose: []
